description: ???

# Debug
action_video:
    save: True                  # Save action video, compare with original

save_pth: True

# Running arguments
debug_index: null
debug_locate: null              # str, e.g. P01_01_42472_42784
index_from: 0
index_to: 99999999
only_cat: null
skip_existing: False

hydra:
    sweep:
        dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
    version: 'v3'  # 'v2 # image_sets: '/home/skynet/Zhifan/data/epic_analysis/gt_clips.json'
    image_sets: ???  # '/home/skynet/Zhifan/epic_analysis/hos/tools/model-input-Feb03.json'

preprocess:
    ihoi_box_expand: 0.3  # 1.0

homan:
    optimize_hand: True 
    optimize_eval_hand: True

    scale_mode: 'scalar'            # Object scale mode: 'depth' / 'scalar' / 'xyz'
    rot_init:
        # Assuming Y-axis is the axis of facing-up and of symmetry
        # If method == 'spiral' or 'upright', 
        #   num_init = num_sphere_pts * num_sym_rots
        # If method == 'upright', '-z' is the outward direction of projection
        #  currently upright is implemented using spiral method.
        # If genearte_on == 'camera', will generate poses on the camera space

        # template:                   
        #     method: 'upright'       # 'spiral', 'upright', 'random'
        #     generate_on: 'camera'   # 'camera' / 'hand'
        #     upright_axis: '-z'      # Required for upright, '+'/'-' for x/y/z 
        #     upright_lim: 0.3        # Required for upright
        #     num_inits: 40            # Required for random
        #     num_sphere_pts: 40      # Required for spiral and upright
        #     num_sym_rots: 1         # Required for spiral and upright

        plate:
            method: 'upright'         # ?
            upright_axis: '-z'          # was +x, now -y?
            upright_lim: 0.3
            generate_on: 'camera'       # face-up in the hand
            num_sphere_pts: -1
            num_sym_rots: 1
        bowl:
            method: 'upright'
            upright_axis: '-z'
            upright_lim: 0.3
            generate_on: 'camera'       # most bowls are still face-up towards camera
            num_sphere_pts: -1
            num_sym_rots: 1
        bottle:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.6            # Allow vertical
            generate_on: 'hand'         # bottle always face-up in the hand
            num_sphere_pts: -1
            num_sym_rots: 1
        cup:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.6            # Allow vertical
            generate_on: 'hand'
            num_sphere_pts: -1
            num_sym_rots: 1
        mug:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.3
            generate_on: 'hand'
            num_sphere_pts: -1
            num_sym_rots: 1
        can:
            method: 'spiral'
            generate_on: 'hand'
            num_sphere_pts: -1
            num_sym_rots: 1

    transl_init_method: 'fingers'   # 'zero' / 'fingers'(finger centers) / 'mask'
    scale_init_method: 'est'        # 'one' / 'xyz' / 'est'
    rotation_regularization: False  # TODO, NotImplmented
    scale_regularization: False

optim_multiview:
    num_source: 100
    num_eval: 30
    num_inits: 510
    num_inits_parallel: 30          # For #-verts == 500, divide by 2
    train_size: 4

    # per epoch
    lr: 1e-2
    num_iters: 50
    vis_interval: -1  # 25
    iter_tqdm: True
    obj_sil_func: l2                # 'l2_iou', 'l2'. Before Feb-25, default is l2_iou
    loss:
        mask:
            weight: 1.0
        inside:
            weight: 1.0
            num_nearest_points: 3   # For each p on obj, number of nearest points in hand
        close:
            weight: 0.1
            num_priors: 5           # 5 for fingers, 8 for all regions
            reduce: 'avg'           # 'avg' / 'min'
            num_nearest_points: 1   # For each p on hand, number of nearest points in obj
        obj_upright:
            weight: 0
            apply_to: {'bowl'}

    criterion: 'iou'