description: ???

# Debug
action_video:
    save: True                  # Save action video, compare with original
    render_frames: ???          # 'ransac' / 'all

save_optim_video: False         # Save optimization video
save_pth: True

# Running arguments
debug_index: null
index_from: 0
index_to: 99999999

hydra:
    sweep:
        dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
    version: 'v3'  # 'v2 # image_sets: '/home/skynet/Zhifan/data/epic_analysis/gt_clips.json'
    image_sets: ???  # '/home/skynet/Zhifan/epic_analysis/hos/tools/model-input-Feb03.json'
    sample_frames: ???

preprocess:
    ihoi_box_expand: 0.3  # 1.0

homan:
    optimize_hand: True 

    scale_mode: 'scalar'            # Object scale mode: 'depth' / 'scalar' / 'xyz'
    rot_init:
        # Assuming Y-axis is the axis of facing-up and of symmetry
        # If method == 'spiral' and 'upright', 
        #   num_init = num_sphere_pts * num_sym_rots
        # If method == 'upright', '-z' is the outward direction of projection
        #  currently upright is implemented using spiral method.
        # If genearte_on == 'camera', will generate poses on the camera space

        # template:                   
        #     method: 'upright'       # 'spiral', 'upright', 'random'
        #     generate_on: 'camera'   # 'camera' / 'hand'
        #     upright_axis: '-z'      # Required for upright, '+'/'-' for x/y/z 
        #     upright_lim: 0.3        # Required for upright
        #     num_init: 40            # Required for random
        #     num_sphere_pts: 40      # Required for spiral and upright
        #     num_sym_rots: 1         # Required for spiral and upright

        plate:
            method: 'upright'         # ?
            upright_axis: '+x'
            upright_lim: 0.3
            generate_on: 'hand'       # face-up in the hand
            num_sphere_pts: 40
            num_sym_rots: 1
        bowl:
            method: 'upright'
            upright_axis: '-z'
            upright_lim: 0.3
            generate_on: 'camera'       # most bowls are still face-up towards camera
            num_sphere_pts: 40
            num_sym_rots: 1
        bottle:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.6            # Allow vertical
            generate_on: 'hand'         # bottle always face-up in the hand
            num_sphere_pts: 40
            num_sym_rots: 1
        cup:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.6            # Allow vertical
            generate_on: 'hand'
            num_sphere_pts: 40
            num_sym_rots: 1
        mug:
            method: 'upright'
            upright_axis: '+z'
            upright_lim: 0.3
            generate_on: 'hand'
            num_sphere_pts: 40
            num_sym_rots: 1
        can:
            method: 'spiral'
            generate_on: 'hand'
            num_sphere_pts: 40
            num_sym_rots: 1

    transl_init_method: 'fingers'   # 'zero' / 'fingers'(finger centers) / 'mask'
    scale_init_method: 'est'        # 'one' / 'xyz' / 'est'
    rotation_regularization: False  # TODO, NotImplmented
    scale_regularization: False

optim_method: ???                     # 'reinit' / 'multiview'
optim:
    loss:
        mask:
            weight: 1.0
        inside:
            weight: 1.0
            num_nearest_points: 3   # For each p on obj, number of nearest points in hand
        close:
            weight: 0.1
            num_priors: 5           # 5 for fingers, 8 for all regions
            reduce: 'avg'           # 'avg' / 'min'
            num_nearest_points: 1   # For each p on hand, number of nearest points in obj
        obj_upright:
            weight: 0
            apply_to: {'bowl'}

    obj_part_prior: False

    lr: 1e-2
    num_epoch_parallel: 1  # 8: 8G, 10: 10G
    epoch_tqdm: True
    num_iters: 50
    iter_tqdm: False
    temperature: 10                 # Required for reinit
    ratio: 0.75                     # Required for reinit
    vis_interval: -1  # 25

    multiview:
        num_source: 100
        num_eval: 25

    criterion: 'iou'