description: ???

# Running arguments
index: ???
save_video: False

hydra:
    sweep:
        dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

dataset:
    image_sets: '/home/skynet/Zhifan/data/epic_analysis/gt_clips.json'
    sample_frames: 30

preprocess:
    ihoi_box_expand: 0.3  # 1.0
    ihoi_img_size: 224
    rend_size: 256

homan:
    scale_mode: ???  # Object scale mode: 'depth' / 'scalar' / 'xyz'

optim:
    loss:
        mask:
            weight: 1.0
        inside:
            weight: 1.0
        close:
            weight: 0.1
            num_priors: 8
            reduce: 'avg' # 'avg' / 'min'

    lr: 1e-2
    num_epochs: 40
    epoch_tqdm: True
    num_iters: 50
    iter_tqdm: False
    temperature: 10
    ratio: 0.75
    vis_interval: -1  # 25

    criteria: 'inside'